version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: categorydb
    ports:
      - "5432:5432"

  categorymodule:
    build:
      context: ./CategoryModule
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: categorydb
    depends_on:
      - db
    ports:
      - "8080:80"
