# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  categorymodule:
    build:
      context: "/Users/congnguyen/RiderProjects/CategoryModule/CategoryModule"
      dockerfile: "Dockerfile"
      target: "build"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "categorymodule:dev"
    ports:
    - "127.0.0.1:57006:57100"
    - "127.0.0.1:57206:57300"
    volumes:
    - "/Users/congnguyen/.nuget/packages:/root/.nuget/packages"
    - "/Users/congnguyen/RiderProjects/CategoryModule/CategoryModule:/app:rw"
    - "/Users/congnguyen/RiderProjects/CategoryModule:/src:rw"
    - "/Users/congnguyen/.local/share/JetBrains/RiderRemoteDebugger/2024.1.4/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/congnguyen/Library/Logs/JetBrains/Rider2024.1/DebuggerWorker/JetBrains.Debugger.Worker.2024_7_17_18_16_02:/var/opt/rider-debugger:rw"
    working_dir: "/app"
